17 tables on 17 Feb 2026

create table public.course_drafts (
  id uuid not null default extensions.uuid_generate_v4 (),
  user_id uuid not null,
  data jsonb not null,
  updated_at timestamp with time zone not null default now(),
  constraint course_drafts_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists course_drafts_user_id_key on public.course_drafts using btree (user_id) TABLESPACE pg_default;






create table public.course_enrollments (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  course_id integer not null,
  enrolled_at timestamp with time zone null default now(),
  progress_id uuid null,
  constraint course_enrollments_pkey primary key (id),
  constraint course_enrollments_user_id_course_id_key unique (user_id, course_id),
  constraint course_enrollments_course_id_fkey foreign KEY (course_id) references courses (id) on delete CASCADE,
  constraint course_enrollments_progress_id_fkey foreign KEY (progress_id) references course_progress (id),
  constraint course_enrollments_user_id_fkey foreign KEY (user_id) references profiles (id) on delete CASCADE
) TABLESPACE pg_default;








create table public.course_media (
  id bigint generated by default as identity not null,
  course_id bigint not null,
  type text not null,
  provider text not null,
  url text not null,
  created_at timestamp with time zone null default now(),
  constraint course_media_pkey primary key (id),
  constraint course_media_course_id_fkey foreign KEY (course_id) references courses (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists course_media_course_id_idx on public.course_media using btree (course_id) TABLESPACE pg_default;







create table public.course_progress (
  id uuid not null default gen_random_uuid (),
  enrollment_id uuid not null,
  progress_percentage integer null default 0,
  last_accessed timestamp with time zone null default now(),
  completed boolean null default false,
  completed_at timestamp with time zone null,
  updated_at timestamp with time zone null default now(),
  constraint course_progress_pkey primary key (id),
  constraint course_progress_enrollment_id_key unique (enrollment_id)
) TABLESPACE pg_default;

create trigger update_course_progress_updated_at BEFORE
update on course_progress for EACH row
execute FUNCTION update_course_progress_updated_at ();













create table public.course_review_notes (
  id uuid not null default gen_random_uuid (),
  course_id integer not null,
  reviewer_id uuid not null,
  content text not null,
  status text not null default 'open'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  addressed boolean null default false,
  constraint course_review_notes_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists course_review_notes_course_id_idx on public.course_review_notes using btree (course_id) TABLESPACE pg_default;

create index IF not exists course_review_notes_reviewer_id_idx on public.course_review_notes using btree (reviewer_id) TABLESPACE pg_default;

create trigger update_course_review_notes_updated_at BEFORE
update on course_review_notes for EACH row
execute FUNCTION update_course_review_notes_updated_at ();











create table public.courses (
  id serial not null,
  title character varying(255) not null,
  slug character varying(255) not null,
  description text null,
  hero_image text null,
  category character varying(50) null,
  level character varying(50) null,
  estimated_hours integer null,
  requirements text null,
  skills text null,
  students integer null default 0,
  rating numeric(2, 1) null default 0,
  featured boolean null default false,
  created_at timestamp without time zone null default now(),
  status text null default 'published'::text,
  published boolean null default false,
  is_paid boolean not null default false,
  constraint courses_pkey primary key (id),
  constraint courses_slug_key unique (slug)
) TABLESPACE pg_default;

create index IF not exists courses_status_idx on public.courses using btree (status) TABLESPACE pg_default;

create index IF not exists courses_published_idx on public.courses using btree (published) TABLESPACE pg_default;








create table public.forum_categories (
  id uuid not null default gen_random_uuid (),
  name text not null,
  description text null,
  slug text not null,
  created_at timestamp with time zone null default now(),
  constraint forum_categories_pkey primary key (id),
  constraint forum_categories_slug_key unique (slug)
) TABLESPACE pg_default;









create table public.forum_posts (
  id uuid not null default gen_random_uuid (),
  topic_id uuid not null,
  user_id uuid not null,
  content text not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint forum_posts_pkey primary key (id),
  constraint forum_posts_topic_id_fkey foreign KEY (topic_id) references forum_topics (id) on delete CASCADE,
  constraint forum_posts_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;

create trigger update_forum_posts_updated_at BEFORE
update on forum_posts for EACH row
execute FUNCTION update_forum_posts_updated_at ();









create table public.forum_topics (
  id uuid not null default gen_random_uuid (),
  title text not null,
  user_id uuid not null,
  category_id uuid not null,
  pinned boolean null default false,
  views integer null default 0,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint forum_topics_pkey primary key (id),
  constraint forum_topics_category_id_fkey foreign KEY (category_id) references forum_categories (id) on delete CASCADE,
  constraint forum_topics_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;

create trigger update_forum_topics_updated_at BEFORE
update on forum_topics for EACH row
execute FUNCTION update_forum_topics_updated_at ();










create table public.lesson_downloads (
  id serial not null,
  lesson_id integer not null,
  title character varying(255) not null,
  description text null,
  file_url text not null,
  file_type character varying(50) not null,
  file_size integer null,
  uploaded_at timestamp with time zone not null default now(),
  modified_at timestamp with time zone not null default now(),
  constraint lesson_downloads_pkey primary key (id),
  constraint lesson_downloads_lesson_id_fkey foreign KEY (lesson_id) references lessons (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists lesson_downloads_lesson_id_idx on public.lesson_downloads using btree (lesson_id) TABLESPACE pg_default;

create trigger set_modified_at BEFORE
update on lesson_downloads for EACH row
execute FUNCTION update_modified_at ();











create table public.lesson_quiz_completions (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  lesson_id integer not null,
  quiz_id uuid not null,
  completed_at timestamp with time zone null default now(),
  constraint lesson_quiz_completions_pkey primary key (id),
  constraint lesson_quiz_completions_user_id_lesson_id_key unique (user_id, lesson_id),
  constraint lesson_quiz_completions_lesson_id_fkey foreign KEY (lesson_id) references lessons (id) on delete CASCADE,
  constraint lesson_quiz_completions_quiz_id_fkey foreign KEY (quiz_id) references quizzes (id) on delete CASCADE,
  constraint lesson_quiz_completions_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;











create table public.lessons (
  id serial not null,
  course_id integer not null,
  title character varying(255) not null,
  description text null,
  estimated_time integer null,
  step_order integer null default 1,
  topics jsonb null,
  video_url text null default 'https://www.youtube.com/watch?v=lEOad0pBh9s'::text,
  constraint lessons_pkey primary key (id),
  constraint lessons_course_id_fkey foreign KEY (course_id) references courses (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger trg_propagate_lesson_course_to_quizzes
after
update OF course_id on lessons for EACH row
execute FUNCTION propagate_lesson_course_to_quizzes ();












create table public.profiles (
  id uuid not null,
  full_name text null,
  avatar_url text null,
  bio text null,
  role text null default 'lawyer'::text,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger update_profiles_updated_at BEFORE
update on profiles for EACH row
execute FUNCTION update_profiles_updated_at ();







create table public.quiz_questions (
  id uuid not null default gen_random_uuid (),
  quiz_id uuid not null,
  questions jsonb not null,
  created_at timestamp with time zone null default now(),
  constraint quiz_questions_pkey primary key (id),
  constraint quiz_questions_quiz_id_fkey foreign KEY (quiz_id) references quizzes (id) on delete CASCADE
) TABLESPACE pg_default;







create table public.quizzes (
  id uuid not null default gen_random_uuid (),
  lesson_id integer not null,
  is_required boolean not null default false,
  created_at timestamp with time zone null default now(),
  course_id integer not null,
  constraint quizzes_pkey primary key (id),
  constraint quizzes_course_id_fkey foreign KEY (course_id) references courses (id) on delete CASCADE,
  constraint quizzes_lesson_id_fkey foreign KEY (lesson_id) references lessons (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_quizzes_course_id on public.quizzes using btree (course_id) TABLESPACE pg_default;

create trigger trg_set_quizzes_course_id BEFORE INSERT
or
update OF lesson_id on quizzes for EACH row
execute FUNCTION set_quizzes_course_id ();






create table public.reviews (
  id serial not null,
  course_id integer null,
  user_name character varying(255) null,
  rating numeric(2, 1) not null,
  comment text null,
  created_at timestamp without time zone null default now(),
  constraint reviews_pkey primary key (id),
  constraint reviews_course_id_fkey foreign KEY (course_id) references courses (id) on delete CASCADE
) TABLESPACE pg_default;









create table public.site_settings (
  id integer not null default 1,
  hero_title text null,
  hero_subtitle text null,
  hero_cta_text text null,
  hero_cta_link text null,
  hero_video_id text null,
  default_theme text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint site_settings_pkey primary key (id),
  constraint site_settings_singleton check ((id = 1))
) TABLESPACE pg_default;

create trigger update_site_settings_updated_at BEFORE
update on site_settings for EACH row
execute FUNCTION update_site_settings_updated_at ();






-- profiles linked to auth users
ALTER TABLE profiles
ADD CONSTRAINT profiles_id_fkey
FOREIGN KEY (id)
REFERENCES auth.users(id)
ON DELETE CASCADE;

-- lessons → courses
ALTER TABLE lessons
ADD CONSTRAINT lessons_course_id_fkey
FOREIGN KEY (course_id)
REFERENCES courses(id)
ON DELETE CASCADE;

-- course enrollments relationships
ALTER TABLE course_enrollments
ADD CONSTRAINT course_enrollments_course_id_fkey
FOREIGN KEY (course_id)
REFERENCES courses(id)
ON DELETE CASCADE;

ALTER TABLE course_enrollments
ADD CONSTRAINT course_enrollments_user_id_fkey
FOREIGN KEY (user_id)
REFERENCES profiles(id)
ON DELETE CASCADE;

ALTER TABLE course_enrollments
ADD CONSTRAINT course_enrollments_progress_id_fkey
FOREIGN KEY (progress_id)
REFERENCES course_progress(id);

-- reviews → courses
ALTER TABLE reviews
ADD CONSTRAINT reviews_course_id_fkey
FOREIGN KEY (course_id)
REFERENCES courses(id)
ON DELETE CASCADE;

-- forum topics
ALTER TABLE forum_topics
ADD CONSTRAINT forum_topics_user_id_fkey
FOREIGN KEY (user_id)
REFERENCES profiles(id);

ALTER TABLE forum_topics
ADD CONSTRAINT forum_topics_category_id_fkey
FOREIGN KEY (category_id)
REFERENCES forum_categories(id)
ON DELETE CASCADE;

-- forum posts
ALTER TABLE forum_posts
ADD CONSTRAINT forum_posts_user_id_fkey
FOREIGN KEY (user_id)
REFERENCES profiles(id);

ALTER TABLE forum_posts
ADD CONSTRAINT forum_posts_topic_id_fkey
FOREIGN KEY (topic_id)
REFERENCES forum_topics(id)
ON DELETE CASCADE;

-- quizzes
ALTER TABLE quizzes
ADD CONSTRAINT quizzes_course_id_fkey
FOREIGN KEY (course_id)
REFERENCES courses(id)
ON DELETE CASCADE;

ALTER TABLE quizzes
ADD CONSTRAINT quizzes_lesson_id_fkey
FOREIGN KEY (lesson_id)
REFERENCES lessons(id)
ON DELETE CASCADE;

-- quiz completions
ALTER TABLE lesson_quiz_completions
ADD CONSTRAINT lesson_quiz_completions_user_id_fkey
FOREIGN KEY (user_id)
REFERENCES auth.users(id)
ON DELETE CASCADE;

ALTER TABLE lesson_quiz_completions
ADD CONSTRAINT lesson_quiz_completions_lesson_id_fkey
FOREIGN KEY (lesson_id)
REFERENCES lessons(id)
ON DELETE CASCADE;

ALTER TABLE lesson_quiz_completions
ADD CONSTRAINT lesson_quiz_completions_quiz_id_fkey
FOREIGN KEY (quiz_id)
REFERENCES quizzes(id)
ON DELETE CASCADE;

-- quiz questions
ALTER TABLE quiz_questions
ADD CONSTRAINT quiz_questions_quiz_id_fkey
FOREIGN KEY (quiz_id)
REFERENCES quizzes(id)
ON DELETE CASCADE;

-- lesson downloads
ALTER TABLE lesson_downloads
ADD CONSTRAINT lesson_downloads_lesson_id_fkey
FOREIGN KEY (lesson_id)
REFERENCES lessons(id)
ON DELETE CASCADE;

-- course media
ALTER TABLE course_media
ADD CONSTRAINT course_media_course_id_fkey
FOREIGN KEY (course_id)
REFERENCES courses(id)
ON DELETE CASCADE;
